
services:
  - type: web
    name: tv-bitget-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WEBHOOK_SECRET
        generateValue: true
